#### Find E and store it in dataset

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import tkinter as tk
from tkinter import filedialog
import seaborn as sns
import numpy as np

In [ ]:
# Ask the user to select a folder containing the data files
root = tk.Tk()
root.withdraw()  # hide the main tkinter window
folder_path = filedialog.askdirectory(title="Please select the folder containing the data files: ")

In [ ]:

# Find list of relative paths to .txt files in all the folders and subfolders of the selected folder
txt_files = []
for root_dir, dirs, files in os.walk(folder_path):
    for file in files:
        if file.endswith(".txt"):
            txt_files.append(os.path.relpath(os.path.join(root_dir, file), folder_path))


#remove those in Calib folder and those ending with position.txt
txt_files = [f for f in txt_files if "Calib" not in f and not f.endswith("position.txt")]

print("List of filtered .txt files:")
for f in txt_files:
    print(f)
print("\n")

# create a df to store the results
results_df = pd.DataFrame(columns=["Folder", "Type of measurement", "Name", "E[eff] (kPa)", "E[v=0.50] (kPa)"])

for l, relative_path in enumerate(txt_files):
    path = os.path.join(folder_path, relative_path)
    parts = os.path.normpath(relative_path).split(os.sep)

    results_df.loc[l, "Name"] = parts[-1]
    results_df.loc[l, "Type of measurement"] = parts[-2]
    results_df.loc[l, "Folder"] = parts[-3]

    with open(path, "r", encoding="latin-1", errors="replace") as f:
        for line in f:
            if "E[eff]" in line:
                results_df.loc[l, "E[eff] (kPa)"] = float(line.strip().split("\t")[-1]) / 1e3
            if "E[v=0.500]" in line:
                results_df.loc[l, "E[v=0.50] (kPa)"] = float(line.strip().split("\t")[-1]) / 1e3

display(results_df)

List of filtered .txt files:
cor_hor_1\Indentations\cor_hor_1 Indentation_001.txt
cor_hor_1\Indentations\cor_hor_1 Indentation_006.txt
cor_hor_1\Indentations\cor_hor_1 Indentation_007.txt
cor_hor_1\Indentations\cor_hor_1 Indentation_008.txt
cor_hor_1\Indentations\cor_hor_1 Indentation_009.txt
cor_hor_1\matrix_scan01\cor_hor_1 S-1 X-1 Y-3 I-1.txt
cor_hor_1\matrix_scan01\cor_hor_1 S-1 X-2 Y-2 I-1.txt
cor_hor_1\matrix_scan01\cor_hor_1 S-1 X-2 Y-3 I-1.txt
cor_hor_2\Indentations\cor_hor_2 Indentation_001.txt
cor_hor_2\Indentations\cor_hor_2 Indentation_002.txt
cor_hor_2\Indentations\cor_hor_2 Indentation_003.txt
cor_hor_2\Indentations\cor_hor_2 Indentation_006.txt
cor_hor_2\Indentations\cor_hor_2 Indentation_009.txt
cor_hor_2\matrix_scan03\cor_hor_2 S-1 X-1 Y-1 I-1.txt
cor_hor_2\matrix_scan03\cor_hor_2 S-1 X-1 Y-2 I-1.txt
cor_hor_2\matrix_scan03\cor_hor_2 S-1 X-1 Y-3 I-1.txt
cor_sag_lat_1.1\matrix_scan01\cor_sag_lat_1.1 S-1 X-1 Y-2 I-1.txt
cor_sag_lat_1.1\matrix_scan01\cor_sag_lat_1.1 S-1 X-1 Y-3 I-1.txt
cor_sag_lat_1.1\matrix_scan01\cor_sag_lat_1.1 S-1 X-1 Y-4 I-1.txt
cor_sag_lat_1.1\matrix_scan01\cor_sag_lat_1.1 S-1 X-1 Y-5 I-1.txt
cor_sag_lat_1.1\matrix_scan01\cor_sag_lat_1.1 S-1 X-2 Y-2 I-1.txt
cor_sag_lat_1.1\matrix_scan01\cor_sag_lat_1.1 S-1 X-2 Y-3 I-1.txt
cor_sag_lat_1.1\matrix_scan01\cor_sag_lat_1.1 S-1 X-2 Y-5 I-1.txt
cor_sag_lat_1.1\matrix_scan01\cor_sag_lat_1.1 S-1 X-3 Y-1 I-1.txt
cor_sag_lat_1.2\matrix_scan01\cor_sag_lat_1.2 S-1 X-1 Y-1 I-1.txt
cor_sag_lat_1.2\matrix_scan01\cor_sag_lat_1.2 S-1 X-1 Y-2 I-1.txt
cor_sag_lat_1.2\matrix_scan01\cor_sag_lat_1.2 S-1 X-1 Y-3 I-1.txt
cor_sag_lat_1.2\matrix_scan01\cor_sag_lat_1.2 S-1 X-2 Y-1 I-1.txt
cor_sag_lat_1.2\matrix_scan01\cor_sag_lat_1.2 S-1 X-2 Y-2 I-1.txt
cor_sag_lat_1.2\matrix_scan01\cor_sag_lat_1.2 S-1 X-2 Y-3 I-1.txt
cor_sag_lat_2.1\matrix_scan01\cor_sag_lat_2.1 S-1 X-1 Y-1 I-1.txt
cor_sag_lat_2.1\matrix_scan01\cor_sag_lat_2.1 S-1 X-1 Y-3 I-1.txt
cor_sag_lat_2.1\matrix_scan01\cor_sag_lat_2.1 S-1 X-2 Y-3 I-1.txt
cor_sag_lat_2.1\matrix_scan02\cor_sag_lat_2.1 S-1 X-1 Y-2 I-1.txt
cor_sag_lat_2.2\matrix_scan01\cor_sag_lat_2.1 S-1 X-1 Y-1 I-1.txt
cor_sag_lat_2.2\matrix_scan01\cor_sag_lat_2.1 S-1 X-2 Y-1 I-1.txt
cor_sag_lat_2.2\matrix_scan02\cor_sag_lat_2.1 S-1 X-1 Y-1 I-1.txt
cor_sag_lat_2.2\matrix_scan02\cor_sag_lat_2.1 S-1 X-1 Y-2 I-1.txt
cor_sag_lat_2.2\matrix_scan02\cor_sag_lat_2.1 S-1 X-1 Y-3 I-1.txt
cor_sag_lat_2.2\matrix_scan02\cor_sag_lat_2.1 S-1 X-2 Y-1 I-1.txt
cor_sag_lat_2.2\matrix_scan02\cor_sag_lat_2.1 S-1 X-2 Y-2 I-1.txt
cor_sag_lat_2.2\matrix_scan02\cor_sag_lat_2.1 S-1 X-2 Y-3 I-1.txt
cor_sag_mid_1\Indentations\cor_sag_mid_1 Indentation_002.txt
cor_sag_mid_1\matrix_scan01\cor_sag_mid_2 S-1 X-1 Y-2 I-1.txt
cor_sag_mid_1\matrix_scan01\cor_sag_mid_2 S-1 X-2 Y-1 I-1.txt
cor_sag_mid_1\matrix_scan01\cor_sag_mid_2 S-1 X-2 Y-3 I-1.txt
cor_sag_mid_1\matrix_scan02\cor_sag_mid_2 S-1 X-2 Y-3 I-1.txt
cor_sag_mid_1\matrix_scan03\cor_sag_mid_1 S-1 X-2 Y-1 I-1.txt
cor_sag_mid_1\matrix_scan03\cor_sag_mid_1 S-1 X-2 Y-2 I-1.txt
cor_sag_mid_1\matrix_scan03\cor_sag_mid_1 S-1 X-2 Y-3 I-1.txt
cor_sag_mid_2\Indentations\cor_sag_mid_2 Indentation_002.txt
cor_sag_mid_2\Indentations\cor_sag_mid_2 Indentation_011.txt
cor_sag_mid_2\Indentations\cor_sag_mid_2 Indentation_012.txt
cor_sag_mid_2\Indentations\cor_sag_mid_2 Indentation_013.txt
cor_sag_mid_2\Indentations\cor_sag_mid_2 Indentation_015.txt
cor_sag_mid_2\Indentations\cor_sag_mid_2 Indentation_016.txt
cor_sag_mid_2\matrix_scan01\cor_sag_mid_2 S-1 X-1 Y-1 I-1.txt
cor_sag_mid_2\matrix_scan01\cor_sag_mid_2 S-1 X-1 Y-2 I-1.txt
cor_sag_mid_2\matrix_scan01\cor_sag_mid_2 S-1 X-1 Y-3 I-1.txt
cor_sag_mid_2\matrix_scan01\cor_sag_mid_2 S-1 X-2 Y-1 I-1.txt
cor_sag_mid_2\matrix_scan01\cor_sag_mid_2 S-1 X-2 Y-2 I-1.txt
med_hor_1\Indentations\med_hor_1 Indentation_001.txt
med_hor_1\Indentations\med_hor_1 Indentation_002.txt
med_hor_1\Indentations\med_hor_1 Indentation_006.txt
med_hor_1\Indentations\med_hor_1 Indentation_007.txt
med_hor_1\Indentations\med_hor_1 Indentation_009.txt
med_hor_1\Indentations\med_hor_1 Indentation_012.txt
med_hor_1\Indentations\med_hor_1 Indentation_013.txt
med_hor_1\Indentations\med_hor_1 Indentation_014.txt
med_hor_1\Indentations\Test Indentation_003.txt
med_hor_1\Indentations\Test Indentation_004.txt
med_hor_1\Indentations\Test Indentation_006.txt
med_hor_2\Indentations\med_hor_2 Indentation_003.txt
med_hor_2\matrix_scan01\med_hor_2 S-1 X-2 Y-1 I-1.txt
med_hor_2\matrix_scan01\med_hor_2 S-1 X-2 Y-2 I-1.txt
med_hor_2\matrix_scan02\med_hor_2 S-1 X-1 Y-1 I-1.txt
med_hor_2\matrix_scan02\med_hor_2 S-1 X-1 Y-2 I-1.txt
med_hor_2\matrix_scan02\med_hor_2 S-1 X-1 Y-3 I-1.txt
med_hor_2\matrix_scan02\med_hor_2 S-1 X-2 Y-1 I-1.txt
med_sag_1\matrix_scan01\med_sag_2 S-1 X-1 Y-1 I-1.txt
med_sag_1\matrix_scan01\med_sag_2 S-1 X-1 Y-3 I-1.txt
med_sag_1\matrix_scan01\med_sag_2 S-1 X-2 Y-1 I-1.txt
med_sag_2\matrix_scan01\med_sag_2 S-1 X-1 Y-2 I-1.txt
med_sag_2\matrix_scan01\med_sag_2 S-1 X-2 Y-2 I-1.txt

,Folder,Type of measurement,Name,E[eff] (kPa),E[v=0.50] (kPa)
0,cor_hor_1,Indentations,cor_hor_1 Indentation_001.txt,0.301943,0.226457
1,cor_hor_1,Indentations,cor_hor_1 Indentation_006.txt,0.794621,0.595966
2,cor_hor_1,Indentations,cor_hor_1 Indentation_007.txt,1.865113,1.398835
3,cor_hor_1,Indentations,cor_hor_1 Indentation_008.txt,2.091576,1.568682
4,cor_hor_1,Indentations,cor_hor_1 Indentation_009.txt,2.087519,1.565639
...,...,...,...,...,...
79,med_sag_1,matrix_scan01,med_sag_2 S-1 X-1 Y-1 I-1.txt,0.732654,0.549491
80,med_sag_1,matrix_scan01,med_sag_2 S-1 X-1 Y-3 I-1.txt,0.906057,0.679543
81,med_sag_1,matrix_scan01,med_sag_2 S-1 X-2 Y-1 I-1.txt,0.022114,0.016585
82,med_sag_2,matrix_scan01,med_sag_2 S-1 X-1 Y-2 I-1.txt,0.223661,0.167745
83,med_sag_2,matrix_scan01,med_sag_2 S-1 X-2 Y-2 I-1.txt,0.109518,0.082138

In [ ]:
# Remove outliers where E value is more than 1 GPa (1e6 kPa)
results_df = results_df[(results_df["E[eff] (kPa)"] < 1e6) & (results_df["E[v=0.50] (kPa)"] < 1e6)]

# Remove Nan values
results_df = results_df.dropna(subset=["E[eff] (kPa)", "E[v=0.50] (kPa)"])

# Save the results to a CSV file
results_df.to_csv(os.path.join(folder_path, "results.csv"), index=False)

display(results_df)

,Folder,Type of measurement,Name,E[eff] (kPa),E[v=0.50] (kPa)
0,cor_hor_1,Indentations,cor_hor_1 Indentation_001.txt,0.301943,0.226457
1,cor_hor_1,Indentations,cor_hor_1 Indentation_006.txt,0.794621,0.595966
2,cor_hor_1,Indentations,cor_hor_1 Indentation_007.txt,1.865113,1.398835
3,cor_hor_1,Indentations,cor_hor_1 Indentation_008.txt,2.091576,1.568682
4,cor_hor_1,Indentations,cor_hor_1 Indentation_009.txt,2.087519,1.565639
...,...,...,...,...,...
79,med_sag_1,matrix_scan01,med_sag_2 S-1 X-1 Y-1 I-1.txt,0.732654,0.549491
80,med_sag_1,matrix_scan01,med_sag_2 S-1 X-1 Y-3 I-1.txt,0.906057,0.679543
81,med_sag_1,matrix_scan01,med_sag_2 S-1 X-2 Y-1 I-1.txt,0.022114,0.016585
82,med_sag_2,matrix_scan01,med_sag_2 S-1 X-1 Y-2 I-1.txt,0.223661,0.167745
83,med_sag_2,matrix_scan01,med_sag_2 S-1 X-2 Y-2 I-1.txt,0.109518,0.082138

In [ ]:
# Aggregate the results by folder and calculate the mean and standard deviation for E[eff] and E[v=0.50]
aggregated_df = results_df.groupby("Folder").agg({"E[eff] (kPa)": ["mean"], "E[v=0.50] (kPa)": ["mean"]})

display(aggregated_df)

                E[eff] (kPa) E[v=0.50] (kPa)
                        mean            mean
Folder
cor_hor_1           0.922763        0.692072
cor_hor_2           0.253679        0.190259
cor_sag_lat_1.1     1.508951        1.131713
cor_sag_lat_1.2     2.664254         1.99819
cor_sag_lat_2.1     2.853644        2.140233
cor_sag_lat_2.2      2.30639        1.729793
cor_sag_mid_1       0.558907         0.41918
cor_sag_mid_2       0.089478        0.067108
med_hor_1           0.555499        0.416624
med_hor_2           0.374115        0.280586
med_sag_1           0.553608        0.415206
med_sag_2            0.16659        0.124942

: