#### Find E and store it in dataset

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import tkinter as tk
from tkinter import filedialog

In [23]:
# Ask the user to select a folder containing the data files
root = tk.Tk()
root.withdraw()  # hide the main tkinter window
folder_path = filedialog.askdirectory(title="Please select the folder containing the data files: ")

In [26]:

# Find list of relative paths to .txt files in all the folders and subfolders of the selected folder
txt_files = []
for root_dir, dirs, files in os.walk(folder_path):
    for file in files:
        if file.endswith(".txt"):
            txt_files.append(os.path.relpath(os.path.join(root_dir, file), folder_path))


#remove those in Calib folder and those ending with position.txt
txt_files = [f for f in txt_files if "Calib" not in f and not f.endswith("position.txt")]

print("List of filtered .txt files:")
for f in txt_files:
    print(f)
print("\n")

# create a df to store the results
results_df = pd.DataFrame(columns=["Name", "Folder", "Header line", "X", "Y", "Count", "E[eff] (kPa)", "E[v=0.50] (kPa)"])


# read text file tracking line until you find "Time (s)" then memorize that line and call it header_line
for l in range(len(txt_files)):
    path = os.path.join(folder_path, txt_files[l])
    results_df.loc[l, "Folder"] = os.path.dirname(txt_files[l])
    # Name is until "S-" in the filename
    results_df.loc[l, "Name"] = os.path.basename(txt_files[l]).split("S-")[0]
    with open(path, 'r', encoding='latin-1', errors='replace') as f:
        for i, line in enumerate(f):
            if "Time (s)" in line:
                results_df.loc[l, "Header line"] = i
                break
            if "E[eff]" in line:
                results_df.loc[l, "E[eff] (kPa)"] = (float(line.strip().split('\t')[-1]))/1e3
            if "E[v=0.50]" in line:
                results_df.loc[l, "E[v=0.50] (kPa)"] = (float(line.strip().split('\t')[-1]))/1e3
            if i == 2:
                parts = line.strip().split('\t')
                for idx, part in enumerate(parts[:-1]):
                    if part == "X (#)":
                        results_df.loc[l, "X"] = float(parts[idx + 1])
                    elif part == "Y (#)":
                        results_df.loc[l, "Y"] = float(parts[idx + 1])


# Add an index count per folder
results_df["Count"] = results_df.groupby("Folder").cumcount() + 1
display(results_df)

# Save the results to a CSV file
results_df.to_csv(os.path.join(folder_path, "results.csv"), index=False)



display(results_df.groupby("Folder").agg({"E[eff] (kPa)": ["mean", "std"], "E[v=0.50] (kPa)": ["mean", "std"]}))

List of filtered .txt files:
matrix_scan01\gelatin 10% F4 S-1 X-1 Y-1 I-1.txt
matrix_scan01\gelatin 10% F4 S-1 X-1 Y-2 I-1.txt
matrix_scan01\gelatin 10% F4 S-1 X-2 Y-1 I-1.txt
matrix_scan01\gelatin 10% F4 S-1 X-2 Y-2 I-1.txt
matrix_scan02\gelatin 10% F4 S-1 X-1 Y-1 I-1.txt

,Name,Folder,Header line,X,Y,Count,E[eff] (kPa),E[v=0.50] (kPa)
0,gelatin 10% F4,matrix_scan01,34,1.0,1.0,1,12.429103,9.321827
1,gelatin 10% F4,matrix_scan01,34,1.0,2.0,2,13.320035,9.990027
2,gelatin 10% F4,matrix_scan01,34,2.0,1.0,3,13.162808,9.872106
3,gelatin 10% F4,matrix_scan01,34,2.0,2.0,4,14.586578,10.939934
4,gelatin 10% F4,matrix_scan02,34,1.0,1.0,1,21.905456,16.429092

              E[eff] (kPa)           E[v=0.50] (kPa)
                      mean       std            mean       std
Folder
matrix_scan01    13.374631  0.896417       10.030973  0.672313
matrix_scan02    21.905456       NaN       16.429092       NaN